import pptxgen from "pptxgenjs"
import { InferenceClient } from "@huggingface/inference"

const hf = new InferenceClient(process.env.HF_TOKEN)

const COLORS = {
  primary: "1E293B",     // Deep Slate
  accent: "2563EB",      // Vibrant Blue
  secondary: "0F172A",   // Dark Background
  text: "334155",        // Body Text
  lightBg: "F8FAFC",     // Card Fill Light
  altBg: "EFF6FF",       // Card Fill Blue
  border: "E2E8F0",      // Card Border
  white: "FFFFFF",
  muted: "64748B"
}

export const generatePpt = async (data) => {
  const ppt = new pptxgen()
  ppt.layout = "LAYOUT_WIDE" // 13.33 x 7.5 inches
  ppt.author = "CortexAI"
  ppt.title = data.title
  ppt.company = "CortexAI"

  // 1. Cover Slide
  addCover(ppt, data)

  // 2. Process Content Slides with Dynamic Layouts & AI Images
  for (let i = 0; i < data.slides.length; i++) {
    const slideData = data.slides[i]
    const pageNum = i + 1
    const totalPages = data.slides.length

    // Alternate layout strategy: Even slides get images, odd slides get grid/card layouts
    if (i % 2 === 0 && slideData.imagePrompt) {
      const imageBase64 = await fetchImageBase64(slideData.imagePrompt)
      if (imageBase64) {
        addSplitImageSlide(ppt, slideData.title, slideData.points, imageBase64, pageNum, totalPages)
      } else {
        addCardGridSlide(ppt, slideData.title, slideData.points, pageNum, totalPages)
      }
    } else {
      addCardGridSlide(ppt, slideData.title, slideData.points, pageNum, totalPages)
    }
  }

  // 3. Closing Slide
  addThankYou(ppt)

  return ppt
}

/** Helper: Fetch Image from Hugging Face FLUX.1 **/
async function fetchImageBase64(prompt) {
  try {
    const blob = await hf.textToImage({
      model: "black-forest-labs/FLUX.1-schnell",
      inputs: `${prompt}, clean presentation graphic, modern vector art, 8k, isolated background`,
    })
    const arrayBuffer = await blob.arrayBuffer()
    return Buffer.from(arrayBuffer).toString("base64")
  } catch (err) {
    console.error("HF Image Fetch Failed:", err?.message || err)
    return null
  }
}

/** 1. Cover Slide **/
const addCover = (ppt, data) => {
  const slide = ppt.addSlide()
  slide.background = { color: COLORS.secondary }

  // Accent Line Bar
  slide.addShape(ppt.ShapeType.rect, {
    x: 0, y: 0, w: 13.33, h: 0.15,
    fill: { color: COLORS.accent },
    line: { color: COLORS.accent }
  })

  // Main Title
  slide.addText(data.title, {
    x: 0.8, y: 2.0, w: 11.7, h: 1.2,
    align: "center", color: COLORS.white,
    bold: true, fontSize: 32, fontFace: "Helvetica"
  })

  // Subtitle
  if (data.subtitle) {
    slide.addText(data.subtitle, {
      x: 1.0, y: 3.3, w: 11.3, h: 0.6,
      align: "center", color: "94A3B8",
      fontSize: 18, fontFace: "Helvetica"
    })
  }

  // Footer Branding
  slide.addText("Generated by CortexAI", {
    x: 0, y: 6.8, w: 13.33, h: 0.3,
    align: "center", color: "64748B",
    fontSize: 11, fontFace: "Helvetica"
  })
}

/** 2. Split Slide: Left Column (Text) + Right Column (AI Image) **/
function addSplitImageSlide(ppt, title, points, imageBase64, page, total) {
  const slide = ppt.addSlide()
  slide.background = { color: COLORS.white }

  // Header Title
  slide.addText(title, {
    x: 0.6, y: 0.4, w: 12, h: 0.5,
    fontSize: 22, bold: true, color: COLORS.primary, fontFace: "Helvetica"
  })

  // Divider Line
  slide.addShape(ppt.ShapeType.line, {
    x: 0.6, y: 0.95, w: 12.1, h: 0,
    line: { color: COLORS.border, width: 1.2 }
  })

  // Left Side: Text Cards
  const totalPoints = Math.min(points.length, 4)
  const cardHeight = totalPoints > 3 ? 1.0 : 1.3
  const gap = 0.2

  points.slice(0, 4).forEach((point, i) => {
    const yPos = 1.2 + i * (cardHeight + gap)

    slide.addShape(ppt.ShapeType.roundRect, {
      x: 0.6, y: yPos, w: 6.5, h: cardHeight,
      fill: { color: i % 2 === 0 ? COLORS.lightBg : COLORS.altBg },
      line: { color: COLORS.border, width: 1 },
      rectRadius: 0.08
    })

    slide.addText(point, {
      x: 0.8, y: yPos + 0.1, w: 6.1, h: cardHeight - 0.2,
      fontSize: 13, color: COLORS.text, fontFace: "Helvetica", fit: "shrink"
    })
  })

  // Right Side: Embedded AI Image Box
  slide.addImage({
    data: `data:image/png;base64,${imageBase64}`,
    x: 7.4, y: 1.2, w: 5.3, h: 5.0,
    sizing: { type: "cover", w: 5.3, h: 5.0 }
  })

  // Footer
  addSlideFooter(ppt, slide, page, total)
}

/** 3. Card Grid Slide: 2x2 Grid Layout for Clean Text Spacing **/
function addCardGridSlide(ppt, title, points, page, total) {
  const slide = ppt.addSlide()
  slide.background = { color: COLORS.white }

  // Header Title
  slide.addText(title, {
    x: 0.6, y: 0.4, w: 12, h: 0.5,
    fontSize: 22, bold: true, color: COLORS.primary, fontFace: "Helvetica"
  })

  // Divider Line
  slide.addShape(ppt.ShapeType.line, {
    x: 0.6, y: 0.95, w: 12.1, h: 0,
    line: { color: COLORS.border, width: 1.2 }
  })

  const visiblePoints = points.slice(0, 4)
  const colWidth = 5.8
  const rowHeight = 2.3
  
  visiblePoints.forEach((point, i) => {
    const col = i % 2
    const row = Math.floor(i / 2)
    
    const xPos = 0.6 + col * (colWidth + 0.5)
    const yPos = 1.2 + row * (rowHeight + 0.3)

    // Main Card
    slide.addShape(ppt.ShapeType.roundRect, {
      x: xPos, y: yPos, w: colWidth, h: rowHeight,
      fill: { color: COLORS.lightBg },
      line: { color: COLORS.border, width: 1 },
      rectRadius: 0.1
    })

    // Index Number Badge
    slide.addShape(ppt.ShapeType.roundRect, {
      x: xPos + 0.2, y: yPos + 0.2, w: 0.5, h: 0.4,
      fill: { color: COLORS.accent },
      line: { color: COLORS.accent },
      rectRadius: 0.05
    })

    slide.addText(`0${i + 1}`, {
      x: xPos + 0.2, y: yPos + 0.2, w: 0.5, h: 0.4,
      align: "center", color: COLORS.white, bold: true, fontSize: 12
    })

    // Text Content
    slide.addText(point, {
      x: xPos + 0.2, y: yPos + 0.7, w: colWidth - 0.4, h: 1.4,
      fontSize: 14, color: COLORS.text, fontFace: "Helvetica", fit: "shrink"
    })
  })

  // Footer
  addSlideFooter(ppt, slide, page, total)
}

/** 4. Thank You Slide **/
const addThankYou = (ppt) => {
  const slide = ppt.addSlide()
  slide.background = { color: COLORS.secondary }

  slide.addText("Thank You", {
    x: 0, y: 2.5, w: 13.33, h: 1.0,
    align: "center", color: COLORS.white,
    bold: true, fontSize: 36, fontFace: "Helvetica"
  })

  slide.addText("Questions & Discussion", {
    x: 0, y: 3.6, w: 13.33, h: 0.5,
    align: "center", color: "94A3B8",
    fontSize: 16, fontFace: "Helvetica"
  })

  slide.addText("Generated by CortexAI", {
    x: 0, y: 6.8, w: 13.33, h: 0.3,
    align: "center", color: "64748B",
    fontSize: 11, fontFace: "Helvetica"
  })
}

/** Helper: Common Slide Footer **/
function addSlideFooter(ppt, slide, page, total) {
  slide.addText("CortexAI", {
    x: 0.6, y: 6.8, w: 2.0, h: 0.3,
    fontSize: 10, color: COLORS.muted, fontFace: "Helvetica"
  })

  slide.addText(`${page} / ${total}`, {
    x: 11.9, y: 6.8, w: 0.8, h: 0.3,
    align: "right", fontSize: 10, color: COLORS.muted, fontFace: "Helvetica"
  })
}